name: Deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: volta-cli/action@v4
            - name: Cache dependencies
              id: cache
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: node_modules-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      node_modules-

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile

            - name: Build
              run: yarn build
              env:
                  NODE_ENV: production
                  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
                  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
                  EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
                  EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
                  EMAILJS_PUBLIC_ID: ${{ secrets.EMAILJS_PUBLIC_ID }}

            - name: Publish to Cloudflare Pages
              uses: cloudflare/pages-action@1
              with:
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  projectName: shimit-blog.com
                  directory: ./dist
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
