name: Deploy

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup node
              uses: volta-cli/action@v4
            - name: Get node version
              id: node
              run: |
                  echo "::set-output name=version::$(node -v)"

            - name: Get node_modules cache
              uses: actions/cache@v3.0.2
              id: node_modules
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
            - name: Install Dependencies
              run: yarn install

            - name: Build
              env:
                  NODE_ENV: production
                  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
                  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
                  EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
                  EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
                  EMAILJS_PUBLIC_ID: ${{ secrets.EMAILJS_PUBLIC_ID }}
              run: yarn build
            - name: Deploy
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.ACCOUNT_ID }}
                  command: pages deploy dist
